set(__QT_DEPLOY_TARGET_diagdev_FILE C:/code/LumenArc/LumenArc_v1.0 remake/build_tmp/Debug/diagdev.exe)
set(__QT_DEPLOY_TARGET_diagdev_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_diagdev_RUNTIME_DLLS C:/code/Qt/6.8.0/msvc2022_64/bin/Qt6Multimediad.dll;C:/code/Qt/6.8.0/msvc2022_64/bin/Qt6Guid.dll;C:/code/Qt/6.8.0/msvc2022_64/bin/Qt6Networkd.dll;C:/code/Qt/6.8.0/msvc2022_64/bin/Qt6Cored.dll)
set(__QT_DEPLOY_TARGET_seektest_FILE C:/code/LumenArc/LumenArc_v1.0 remake/build_tmp/Debug/seektest.exe)
set(__QT_DEPLOY_TARGET_seektest_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_seektest_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_seekbench_FILE C:/code/LumenArc/LumenArc_v1.0 remake/build_tmp/Debug/seekbench.exe)
set(__QT_DEPLOY_TARGET_seekbench_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_seekbench_RUNTIME_DLLS )
